# Collector specific configuration
#TODO add details below to github secrets
url: "test"
account: "account"
container: "container"
blob_dir: "blob_dir"
alerts_filename: "output/signals.csv"
locations_filename: "output/signals_locations_metadata.csv"
key: "key"

lat_lon_file_source: "https://gist.githubusercontent.com/tadast/8827699/raw/61b2107766d6fd51e2bd02d9f78f6be081340efc/countries_codes_and_coordinates.csv"

dataset_names:
  HDX-SIGNALS: "hdx-signals"

allowed_tags:
  - "food security"
  - "conflict-violence"
  - "markets"
  - "drought"
  - "displacement"
  - "agriculture-livestock"

# Metadata
title: "HDX Signals"
update_frequency: "weekly"
maintainer_id: "2f9fd160-2a16-49c0-89d6-0bc3230599bf"
organization_id: "hdx"
description_alerts_file: "File of historical signals, containing all email content, from all text in the email, key figures, and hyperlinks to images, original sources, and individual emails."
description_locations_file: "Location-level metadata file with location name, regional classifications, and up-to-date coverage indicating whehter it is included in each of the datasets monitored in HDX Signals."
notes: "HDX Signals monitors key datasets and generates automated emails when significant, negative changes are detected. Receive signals direct in your inbox by signing up on the [home page](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata.humdata.org%2Fsignals&data=05%7C02%7Cisabelle.tot%40un.org%7Cef19ac36eb2446def80508dc7a4cb394%7C0f9e35db544f4f60bdcc5ea416e6dc70%7C0%7C0%7C638519717049783120%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ZvGD7L45DptYgKrWn2qOjs3HN5U6M2DwL9qjYKCI5Gs%3D&reserved=0). Explore historical signals and access all email content in the resources below."
visualization_link: "https://data.humdata.org/visualization/signals"
